/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Role = IDL.Variant({
  'fan' : IDL.Null,
  'supporter' : IDL.Null,
  'player' : IDL.Null,
});
export const Member = IDL.Record({
  'signupTime' : Time,
  'name' : IDL.Text,
  'role' : Role,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
  'register' : IDL.Func([IDL.Text, IDL.Text, Role], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Role = IDL.Variant({
    'fan' : IDL.Null,
    'supporter' : IDL.Null,
    'player' : IDL.Null,
  });
  const Member = IDL.Record({
    'signupTime' : Time,
    'name' : IDL.Text,
    'role' : Role,
    'email' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
    'register' : IDL.Func([IDL.Text, IDL.Text, Role], [], []),
  });
};

export const init = ({ IDL }) => { return []; };