/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Member {
  'signupTime' : Time,
  'name' : string,
  'role' : Role,
  'email' : string,
}
export type Role = { 'fan' : null } |
  { 'supporter' : null } |
  { 'player' : null };
export type Time = bigint;
export interface _SERVICE {
  'getAllMembers' : ActorMethod<[], Array<Member>>,
  'register' : ActorMethod<[string, string, Role], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];